#!/bin/sh
export PATH=/opt/ibm/java/bin:/opt/ibm/wlp/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:$PATH
export LOG_DIR=/logs
export WLP_OUTPUT_DIR=/opt/ibm/wlp/output
export DB2_HOME=/opt/ibm/db2/V11.1
export STERLING_DB=scdb
export JENKINS_HOME=/var/jenkins_home
export JENKINS_SLAVE_AGENT_PORT=${agent_port}
export JENKINS_UC=https://updates.jenkins.io
export JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
export COPY_REFERENCE_FILE_LOG=$JENKINS_HOME/copy_reference_file.log